name: klods

services:
  # https://github.com/felipewom/docker-compose-postgres/blob/main/README.md
  postgres:
    image: 'postgres:17'
    ports:
      - 5105:5432
    env_file:
      - .env
    networks:
      - klods-network
    volumes:
      - klods-db-volume:/var/lib/postgresql/data/:rw
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  pgwebadmin:
    image: dpage/pgadmin4
    ports:
      - 5102:80
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    networks:
      - klods-network
    volumes:
      - klods-pgadmin-volume:/var/lib/pgadmin/:rw

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "5103:9000"
      - "5104:9001"
    env_file:
      - .env
    networks:
      - klods-network
    volumes:
      - klods-minio-volume:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  klods_api:
    image: klods_api
    build:
      context: .
      dockerfile: Klods.Api/Dockerfile
    env_file:
      - .env
    environment:
      BLAZOR_ORIGIN: "${BLAZOR_ORIGIN:-http://localhost:5100}"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      minio:
        condition: service_healthy
        restart: true
    ports:
      - "5101:8080"
    networks:
      - klods-network

  klods_web:
    image: klods_web
    build:
      context: .
      dockerfile: Klods.Web/Dockerfile
    env_file:
      - .env
    environment:
      API_BASE_URL: "http://klods_api:8080"
      API_PUBLIC_URL: "${API_PUBLIC_URL:-http://localhost:5101}"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      minio:
        condition: service_healthy
        restart: true
      klods_api:
        condition: service_started
        restart: true
    ports:
      - "5100:8080"
    networks:
      - klods-network
    volumes:
      - klods-volume:/home/app/.local/share:rw

volumes:
  klods-volume:
  klods-db-volume:
  klods-pgadmin-volume:
  klods-minio-volume:

networks:
  klods-network:
    driver: bridge
