// <auto-generated />
using System;
using Klods.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Klods.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20251129020938_RemoveOwnedBuildCount")]
    partial class RemoveOwnedBuildCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Klods.Brick", b =>
                {
                    b.Property<string>("PartNum")
                        .HasColumnType("text");

                    b.Property<string>("ColorId")
                        .HasColumnType("text");

                    b.Property<string>("ColorName")
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("HexColor")
                        .HasColumnType("text");

                    b.Property<bool>("IsTrans")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartImg")
                        .HasColumnType("text");

                    b.Property<string>("PartURL")
                        .HasColumnType("text");

                    b.HasKey("PartNum", "ColorId");

                    b.ToTable("Bricks");
                });

            modelBuilder.Entity("Klods.Color", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsTrans")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("Klods.Minifig", b =>
                {
                    b.Property<string>("MinifigId")
                        .HasColumnType("text");

                    b.Property<string>("MinifigImgUrl")
                        .HasColumnType("text");

                    b.Property<string>("MinifigName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinifigUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("MinifigId");

                    b.ToTable("Minifigs");
                });

            modelBuilder.Entity("Klods.MinifigBrick", b =>
                {
                    b.Property<string>("MinifigID")
                        .HasColumnType("text");

                    b.Property<string>("BrickID")
                        .HasColumnType("text");

                    b.Property<string>("ColorId")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("MinifigID", "BrickID", "ColorId");

                    b.HasIndex("BrickID", "ColorId");

                    b.ToTable("MinifigBricks");
                });

            modelBuilder.Entity("Klods.Set", b =>
                {
                    b.Property<string>("SetId")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManualUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumBricks")
                        .HasColumnType("integer");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("SetImg")
                        .HasColumnType("text");

                    b.Property<string>("SetURL")
                        .HasColumnType("text");

                    b.HasKey("SetId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("Klods.SetBrick", b =>
                {
                    b.Property<string>("PartNum")
                        .HasColumnType("text");

                    b.Property<string>("ColorId")
                        .HasColumnType("text");

                    b.Property<string>("SetId")
                        .HasColumnType("text");

                    b.Property<int>("SetIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("SpareCount")
                        .HasColumnType("integer");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("PartNum", "ColorId", "SetId", "SetIndex");

                    b.HasIndex("SetId", "SetIndex");

                    b.ToTable("SetBricks");
                });

            modelBuilder.Entity("Klods.SetMinifig", b =>
                {
                    b.Property<string>("MinifigId")
                        .HasColumnType("text");

                    b.Property<string>("SetId")
                        .HasColumnType("text");

                    b.Property<int>("SetIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("MinifigId", "SetId", "SetIndex");

                    b.HasIndex("SetId", "SetIndex");

                    b.ToTable("SetMinifig");
                });

            modelBuilder.Entity("Klods.SetOwned", b =>
                {
                    b.Property<string>("SetId")
                        .HasColumnType("text");

                    b.Property<int>("SetIndex")
                        .HasColumnType("integer");

                    b.HasKey("SetId", "SetIndex");

                    b.ToTable("SetsOwned");
                });

            modelBuilder.Entity("Klods.MinifigBrick", b =>
                {
                    b.HasOne("Klods.Minifig", null)
                        .WithMany()
                        .HasForeignKey("MinifigID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klods.Brick", null)
                        .WithMany()
                        .HasForeignKey("BrickID", "ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klods.SetBrick", b =>
                {
                    b.HasOne("Klods.Brick", null)
                        .WithMany()
                        .HasForeignKey("PartNum", "ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klods.SetOwned", null)
                        .WithMany()
                        .HasForeignKey("SetId", "SetIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klods.SetMinifig", b =>
                {
                    b.HasOne("Klods.Minifig", null)
                        .WithMany()
                        .HasForeignKey("MinifigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klods.SetOwned", null)
                        .WithMany()
                        .HasForeignKey("SetId", "SetIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klods.SetOwned", b =>
                {
                    b.HasOne("Klods.Set", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
