// <auto-generated />
using System;
using Klods.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Klods.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20260713234123_AddMascotVariant")]
    partial class AddMascotVariant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Klods.Brick", b =>
                {
                    b.Property<string>("PartNum")
                        .HasColumnType("text");

                    b.Property<string>("ColorId")
                        .HasColumnType("text");

                    b.Property<string>("BrickOwlId")
                        .HasColumnType("text");

                    b.Property<string>("BricklinkId")
                        .HasColumnType("text");

                    b.Property<string>("ColorName")
                        .HasColumnType("text");

                    b.Property<string>("ElementId")
                        .HasColumnType("text");

                    b.Property<string>("HexColor")
                        .HasColumnType("text");

                    b.Property<bool>("IsTrans")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PartCatId")
                        .HasColumnType("integer");

                    b.Property<string>("PartImg")
                        .HasColumnType("text");

                    b.Property<string>("PartURL")
                        .HasColumnType("text");

                    b.Property<int>("SetCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("PartNum", "ColorId");

                    b.ToTable("Bricks");
                });

            modelBuilder.Entity("Klods.BrickOwned", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("PartNum")
                        .HasColumnType("text");

                    b.Property<string>("ColorId")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "PartNum", "ColorId");

                    b.HasIndex("PartNum", "ColorId");

                    b.ToTable("BrickOwned");
                });

            modelBuilder.Entity("Klods.CatalogImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SnapshotDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CatalogImports");
                });

            modelBuilder.Entity("Klods.Color", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsTrans")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("Klods.Database.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<double>("FontScale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0);

                    b.Property<bool>("HasSeenTour")
                        .HasColumnType("boolean");

                    b.Property<string>("MascotVariant")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryColor")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("User");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("UserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Klods.Database.UserExternalLogin", b =>
                {
                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Provider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserExternalLogins");
                });

            modelBuilder.Entity("Klods.Minifig", b =>
                {
                    b.Property<string>("MinifigId")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumParts")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("MinifigId");

                    b.ToTable("Minifigs");
                });

            modelBuilder.Entity("Klods.MinifigBrick", b =>
                {
                    b.Property<string>("MinifigId")
                        .HasColumnType("text");

                    b.Property<string>("PartNum")
                        .HasColumnType("text");

                    b.Property<string>("ColorId")
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("SpareCount")
                        .HasColumnType("integer");

                    b.HasKey("MinifigId", "PartNum", "ColorId");

                    b.HasIndex("PartNum", "ColorId");

                    b.ToTable("MinifigBricks");
                });

            modelBuilder.Entity("Klods.MinifigBrickOwned", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("MinifigId")
                        .HasColumnType("text");

                    b.Property<int>("MinifigIndex")
                        .HasColumnType("integer");

                    b.Property<string>("PartNum")
                        .HasColumnType("text");

                    b.Property<string>("ColorId")
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "MinifigId", "MinifigIndex", "PartNum", "ColorId");

                    b.HasIndex("MinifigId", "PartNum", "ColorId");

                    b.ToTable("MinifigBrickOwned");
                });

            modelBuilder.Entity("Klods.MinifigOwned", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("MinifigId")
                        .HasColumnType("text");

                    b.Property<int>("MinifigIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("SetId")
                        .HasColumnType("text");

                    b.Property<int?>("SetIndex")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "MinifigId", "MinifigIndex");

                    b.HasIndex("MinifigId");

                    b.HasIndex("UserId", "SetId", "SetIndex");

                    b.ToTable("MinifigOwned");
                });

            modelBuilder.Entity("Klods.PartCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PartCategories");
                });

            modelBuilder.Entity("Klods.Set", b =>
                {
                    b.Property<string>("SetId")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManualUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumBricks")
                        .HasColumnType("integer");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("SetImg")
                        .HasColumnType("text");

                    b.Property<string>("SetURL")
                        .HasColumnType("text");

                    b.Property<int?>("ThemeId")
                        .HasColumnType("integer");

                    b.HasKey("SetId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("Klods.SetBrick", b =>
                {
                    b.Property<string>("SetId")
                        .HasColumnType("text");

                    b.Property<string>("PartNum")
                        .HasColumnType("text");

                    b.Property<string>("ColorId")
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("SpareCount")
                        .HasColumnType("integer");

                    b.HasKey("SetId", "PartNum", "ColorId");

                    b.HasIndex("PartNum", "ColorId");

                    b.ToTable("SetBricks");
                });

            modelBuilder.Entity("Klods.SetBrickOwned", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("SetId")
                        .HasColumnType("text");

                    b.Property<int>("SetIndex")
                        .HasColumnType("integer");

                    b.Property<string>("PartNum")
                        .HasColumnType("text");

                    b.Property<string>("ColorId")
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "SetId", "SetIndex", "PartNum", "ColorId");

                    b.HasIndex("SetId", "PartNum", "ColorId");

                    b.ToTable("SetBrickOwned");
                });

            modelBuilder.Entity("Klods.SetBrickSubstitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PulledFromLoose")
                        .HasColumnType("integer");

                    b.Property<string>("ReqColorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReqPartNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SetIndex")
                        .HasColumnType("integer");

                    b.Property<string>("SubColorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubPartNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubPartNum", "SubColorId");

                    b.HasIndex("SetId", "ReqPartNum", "ReqColorId");

                    b.HasIndex("UserId", "SetId", "SetIndex");

                    b.ToTable("SetBrickSubstitutions");
                });

            modelBuilder.Entity("Klods.SetMinifig", b =>
                {
                    b.Property<string>("SetId")
                        .HasColumnType("text");

                    b.Property<string>("MinifigId")
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("SetId", "MinifigId");

                    b.HasIndex("MinifigId");

                    b.ToTable("SetMinifig");
                });

            modelBuilder.Entity("Klods.SetOwned", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("SetId")
                        .HasColumnType("text");

                    b.Property<int>("SetIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("UserId", "SetId", "SetIndex");

                    b.HasIndex("SetId");

                    b.ToTable("SetsOwned");
                });

            modelBuilder.Entity("Klods.SetUpdateNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.HasIndex("UserId", "ReadAt");

                    b.ToTable("SetUpdateNotifications");
                });

            modelBuilder.Entity("Klods.SetUpdateNotificationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NewCount")
                        .HasColumnType("integer");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer");

                    b.Property<int>("OldCount")
                        .HasColumnType("integer");

                    b.Property<string>("PartNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.ToTable("SetUpdateNotificationItems");
                });

            modelBuilder.Entity("Klods.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Klods.Theme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("Klods.BrickOwned", b =>
                {
                    b.HasOne("Klods.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klods.Brick", null)
                        .WithMany()
                        .HasForeignKey("PartNum", "ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klods.Database.UserExternalLogin", b =>
                {
                    b.HasOne("Klods.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klods.MinifigBrick", b =>
                {
                    b.HasOne("Klods.Minifig", null)
                        .WithMany()
                        .HasForeignKey("MinifigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klods.Brick", null)
                        .WithMany()
                        .HasForeignKey("PartNum", "ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klods.MinifigBrickOwned", b =>
                {
                    b.HasOne("Klods.MinifigBrick", null)
                        .WithMany()
                        .HasForeignKey("MinifigId", "PartNum", "ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klods.MinifigOwned", null)
                        .WithMany()
                        .HasForeignKey("UserId", "MinifigId", "MinifigIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klods.MinifigOwned", b =>
                {
                    b.HasOne("Klods.Minifig", null)
                        .WithMany()
                        .HasForeignKey("MinifigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klods.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klods.SetOwned", null)
                        .WithMany()
                        .HasForeignKey("UserId", "SetId", "SetIndex");
                });

            modelBuilder.Entity("Klods.SetBrick", b =>
                {
                    b.HasOne("Klods.Set", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klods.Brick", null)
                        .WithMany()
                        .HasForeignKey("PartNum", "ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klods.SetBrickOwned", b =>
                {
                    b.HasOne("Klods.SetBrick", null)
                        .WithMany()
                        .HasForeignKey("SetId", "PartNum", "ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klods.SetOwned", null)
                        .WithMany()
                        .HasForeignKey("UserId", "SetId", "SetIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klods.SetBrickSubstitution", b =>
                {
                    b.HasOne("Klods.Brick", null)
                        .WithMany()
                        .HasForeignKey("SubPartNum", "SubColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klods.SetBrick", null)
                        .WithMany()
                        .HasForeignKey("SetId", "ReqPartNum", "ReqColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klods.SetOwned", null)
                        .WithMany()
                        .HasForeignKey("UserId", "SetId", "SetIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klods.SetMinifig", b =>
                {
                    b.HasOne("Klods.Minifig", null)
                        .WithMany()
                        .HasForeignKey("MinifigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klods.Set", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klods.SetOwned", b =>
                {
                    b.HasOne("Klods.Set", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klods.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klods.SetUpdateNotification", b =>
                {
                    b.HasOne("Klods.Set", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Klods.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klods.SetUpdateNotificationItem", b =>
                {
                    b.HasOne("Klods.SetUpdateNotification", null)
                        .WithMany("Items")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klods.SetUpdateNotification", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
