<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>Klods</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Klods.Core\Klods.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="DotNetEnv" Version="3.1.1" />
        <PackageReference Include="MudBlazor" Version="8.15.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
        <None Include="wwwroot\images\lit.ico" />
        <None Include="wwwroot\images\lit.png" />
        <None Include="wwwroot\images\lit.xcf" />
    </ItemGroup>

</Project>
