version: "3"
services:
  lego_inventory:
    image: lego_inventory
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    network_mode: "host"
    volumes:
      - data-volume:/home/app/.local/share:rw
volumes:
  data-volume: