// <auto-generated />
using System;
using LEGO_Inventory.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LEGO_Inventory.Migrations
{
    [DbContext(typeof(InventoryContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LEGO_Inventory.Brick", b =>
                {
                    b.Property<string>("PartNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HexColor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTrans")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartImg")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartURL")
                        .HasColumnType("TEXT");

                    b.HasKey("PartNum", "ColorId");

                    b.ToTable("Bricks");
                });

            modelBuilder.Entity("LEGO_Inventory.Minifig", b =>
                {
                    b.Property<string>("MinifigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinifigImgUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinifigName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinifigUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MinifigId");

                    b.ToTable("Minifigs");
                });

            modelBuilder.Entity("LEGO_Inventory.Set", b =>
                {
                    b.Property<string>("SetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BuildCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManualUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinifigCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumBricks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetImg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SetId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("LEGO_Inventory.SetBrick", b =>
                {
                    b.Property<string>("PartNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpareCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("PartNum", "ColorId", "SetId");

                    b.HasIndex("SetId");

                    b.ToTable("SetBricks");
                });

            modelBuilder.Entity("LEGO_Inventory.SetMinifig", b =>
                {
                    b.Property<string>("MinifigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("MinifigId", "SetId");

                    b.HasIndex("SetId");

                    b.ToTable("SetMinifig");
                });

            modelBuilder.Entity("LEGO_Inventory.SetBrick", b =>
                {
                    b.HasOne("LEGO_Inventory.Set", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LEGO_Inventory.Brick", null)
                        .WithMany()
                        .HasForeignKey("PartNum", "ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LEGO_Inventory.SetMinifig", b =>
                {
                    b.HasOne("LEGO_Inventory.Minifig", null)
                        .WithMany()
                        .HasForeignKey("MinifigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LEGO_Inventory.Set", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
